export const ADD_REQUESTS = 'ADD_REQUESTS';
export const ADD_REQUESTS_START = 'ADD_REQUESTS_START';
export const ADD_REQUESTS_FAIL = 'ADD_REQUESTS_FAIL';
export const ADD_REQUESTS_SUCCESS = 'ADD_REQUESTS_SUCCESS';
export const REMOVED_TO_FALSE_REQUEST = 'REMOVED_TO_FALSE_REQUEST';

export const REMOVE_REQUESTS = 'REMOVE_REQUESTS';
export const REMOVE_REQUESTS_START = 'REMOVE_REQUESTS_START';
export const REMOVE_REQUESTS_FAIL = 'REMOVE_REQUESTS_FAIL';
export const REMOVE_REQUESTS_SUCCESS = 'REMOVE_REQUESTS_SUCCESS';
export const REMOVED_TO_FALSE = 'REMOVED_TO_FALSE';

export const FETCH_REQUESTS_START = 'FETCH_REQUESTS_START';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_FAIL = 'FETCH_REQUESTS_FAIL';
export const FECTH_APPROVE_SUCCESS='FECTH_APPROVE_SUCCESS';
export const FECTH_REJECT_SUCCESS='FECTH_REJECT_SUCCESS';
export const FETCH_BUDGET_SUCCESS='FETCH_BUDGET_SUCCESS';
export const FETCH_BUDGET_REJECT='FETCH_BUDGET_REJECT';
export const FETCH_DRIVER_SUCCESS='FETCH_DRIVER_SUCCESS';
export const ASSING_DRIVER_SUCCESS='ASSING_DRIVER_SUCCESS';
export const UPDATE_ITEMS_SUCCESS='UPDATE_ITEMS_SUCCESS';

export const DISMISS_ALERT='DISMISS_ALERT';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCSESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const FETCH_SUCCESS_USERS= 'FETCH_SUCCESS_USERS';
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS';
export const ADD_USER_START='ADD_USER_START';

export const FETCH_COMPANIES_SUCCESS='FETCH_COMPANIES_SUCCESS';
export const ADD_COMPANY_SUCCESS='ADD_COMPANY_SUCCESS';
export const FETCH_COMPANY_START='FETCH_COMPANY_START';

export const FETCH_BUILDINGS_SUCCESS='FETCH_BUILDINGS_SUCCESS';
export const ADD_BUILDING_SUCCESS='ADD_BUILDING_SUCCESS';
export const FETCH_BUILDING_START='FETCH_BUILDING_START';


export const ADD_BUDGET_SUCCESS='ADD_BUDGET_SUCCESS'